### ISSUE TITLE
Add Meetup Data for Counties and number of meetups

### ISSUE THREAD

**Issue by Davidutro** [makerdao/commdev-grants-transparency-dashboard#15]
Title self-explanatory

Here's the data for the life of the progam

Country | Number of funded meetups
-- | --
Argentina | 11
Armenia | 1
Australia | 1
Brazil | 1
Canada | 1
Chile | 1
China | 1
Colombia | 4
Ecuador | 1
England | 2
France | 2
Germany | 1
Ghana | 17
Greece | 2
Honduras | 1
Indonesia | 1
Kuwait | 1
Mexico | 3
Netherlands | 1
Nigeria | 7
Norway | 1
Philippines | 4
Qatar | 1
Serbia | 1
Slovakia | 2
Slovenia | 1
Spain | 4
Switzerland | 1
Tanzania | 2
Thailand | 3
Turkey | 1
Uganda | 8
USA | 10

**Comment by isaacpearl** [comment]
Currently, all data points in ```publicData.json``` are represented by two properties: the raw data, and a simple sentence describing the data point, as in:
```
// ...
"applicationsSubmitted": 11,
"whatAreApplicationsSubmitted": "The total applications that have been submitted to the Meetup grants program",
// ...
```
Should I include a ```"whatAreCountryMeetupCounts"``` sentence alongside the ```"countryMeetupCounts"``` I'm adding here, and if so, is there any specific copy you'd like me to use? I currently have "The total number of funded meetups by country" added as a placeholder.

**Comment by Davidutro** [comment]
"The total number of funded meetups by country" sounds exactly right. If I think of a better phrasing I'll comment here on the issue :))
