### ISSUE TITLE
Fix existing Test checking Data from Failing

### ISSUE THREAD

**Issue by MaximumCrash** [makerdao/commdev-grants-transparency-dashboard#18]
attn: @isaacpearl 
cc: @as-dr 
In relation to [CDIP-10](https://docs.google.com/document/d/1MJD5tT2265eRh80Nw5dxtuGB_z0zGPhJ8BZfUbjw9rE/edit) specifically **Milestone 3** for QA and Testing

# The Problem
- Currently when you run ```npm run test``` the test fails. 
- We also see that the existing Travis CLI testing suite fails when submitting a PR. 

# Deliverable 
- Existing ```npm run test``` passes without issue 

# Nice to Have, but not Necessary
- Travis CLI stops failing after the PR has been submitted. Yet this is a chicken and egg situation so we'd need another PR to prove this is the case.

**Comment by isaacpearl** [comment]
attn: @MaximumCrash 
cc: @as-dr 

Fixing the test was a quick task (there were labels being used in the JSON that had to be added to ```dataformat.js```, and legitimately missing data for Sablier and Ramp.Networks), but there's a larger issue that the change raised:
- Adding the missing "Enjoy Dai" type to dataformat.js causes a new button to render under the explore panel, and the existing row of buttons is now too wide:
![Screenshot from 2020-04-14 19-09-39](https://user-images.githubusercontent.com/21342523/79282592-9a22aa00-7e83-11ea-9f99-087bb8e013e8.png)
     - This could be fixed with a pretty simple css change (either changing the spacing or button size), or by merging "Enjoy Dai" with one of the other project types to avoid the frontend issues entirely.
     - @as-dr what approach makes the most sense to you? I'm hesitant to make changes to the core data or the design without checking in.

**Comment by as-dr** [comment]
I actually set it up to overflow like this ;) but it’s easily fixed if we want to.

**Comment by isaacpearl** [comment]
All good! I'll make this PR now ~
