### ISSUE TITLE
Implement countries data in Meetup page

### ISSUE THREAD

**Issue by as-dr** [makerdao/commdev-grants-transparency-dashboard#25]
# To Do
1. - [x] Add up meetup country data into regions (North America, South America, Europe, Africa, Asia, Oceania)
1. - [x] Add those country numbers to a Meetup-specific "regions" data object
1. - [x] Import the "country" region into the Meetups page and display at at the top of the list of Stats (refer to reference)

# Reference
![image](https://user-images.githubusercontent.com/6787950/79974613-05fea700-8470-11ea-8514-05adbd2152ca.png)

**Comment by as-dr** [comment]
@amy-jung Here's an alternative approach where the country container doesn't overflow, so you can see all the countries at once. Think this can work too, since there's less data on this page.
![image](https://user-images.githubusercontent.com/6787950/79974729-38100900-8470-11ea-8941-6e33a502c465.png)

**Comment by amy-jung** [comment]
Yup it looks good!

**Comment by MaximumCrash** [comment]
@as-dr Question, since the countryMeetupCounts data is more fleshed out (by country and not by region) I think it may be tedious to render them as individual cards like we do on the grants page (especially since there are 33 countries. I'd suggest a geo map like this https://nivo.rocks/choropleth/ lemme know your thoughts.

**Comment by as-dr** [comment]
I was thinking of just adding them all up by region per the first to-do. It’s tedious but shouldn’t take more than 30 mins. My concern with that geo map addon is that it doesn’t appear to visualize the data without hovering over it, and also the responsiveness of the map itself.

**Comment by MaximumCrash** [comment]
@as-dr Sounds like a plan

**Comment by as-dr** [comment]
### North America
### 14
Canada | 1
Mexico | 3
USA | 10


### South America
### 19
Argentina | 11
Brazil | 1
Chile | 1
Colombia | 4
Ecuador | 1
Honduras | 1



### Africa
### 34
Ghana | 17
Nigeria | 7
Tanzania | 2
Uganda | 8


### Europe
### 19
England | 2
France | 2
Germany | 1
Greece | 2
Netherlands | 1
Norway | 1
Serbia | 1
Slovakia | 2
Slovenia | 1
Spain | 4
Switzerland | 1
Turkey | 1




### Asia
### 8
China | 1
Armenia | 1
Kuwait | 1
Indonesia | 1
Qatar | 1
Thailand | 3



### Oceania
### 5
Australia | 1
Philippines | 4
