### ISSUE TITLE
Setup JSON file with Meetup data

### ISSUE THREAD

**Issue by as-dr** [makerdao/commdev-grants-transparency-dashboard#7]
Per David's post here: https://github.com/makerdao/commdev-grants-transparency-dashboard/issues/4#issuecomment-602698638 we need to create a new JSON file to store this data, in the same vein as the grants program data.

# To Do
1. - [x] Update `publicData.json` file and add the meetups data, structured and populated in the same way as it's expressed in [this post](https://github.com/makerdao/commdev-grants-transparency-dashboard/issues/4#issuecomment-602698638). I'd recommend creating two new "parent" arrays to organize "grants" and "meetups" data separately.
1. - [x] Update `utils.js` `data` object to correctly pull in new meetups data from the JSON, so we can populate the front end.

@MaximumCrash Are the instructions laid out here technically accurate per your v1.5 implementation approach / refactor?

**Comment by isaacpearl** [comment]
I can't assign this to myself yet, but I'll take care of this one!

**Comment by isaacpearl** [comment]
Is there a specific reason that a single-element array would be better to hold the objects for grant/meetup data, or would it be okay to just use nested objects? (```publicData.meetups[0]``` vs ```publicData.meetups```)

**Comment by MaximumCrash** [comment]
@as-dr correct if I'm wrong. @isaacpearl It could be that's just how the data may have been exported from airtable. If that's the case it may be safer to expect that it will always be a single element array and to massage the data to meet your needs.

**Comment by isaacpearl** [comment]
@MaximumCrash that makes sense! I left it expecting a single-element array for now, and it's a trivial change to 2 lines at the top of ```utils.js``` it if we need/want to switch it later.

@as-dr - Is there any meetups data we'd want ```utils.js``` to return that isn't in ```publicData.json```? The grants data object has a few fields that are the results of aggregating data from ```acceptedProjectsData.json```, and I wanted to see if there might be any similar needs for our meetup data.

**Comment by as-dr** [comment]
@isaacpearl Great question. It is *possible* that we will need to, but it has not been requested just yet. 

Where might we need to setup calculations? The first two that come to mind:

1. To show percentages that we can graph with `chartjs` e.g. % of repeat hosts (by calculating # of uniques against # of repeats)
1. To show averages, e.g. average amount of Dai awarded per meetup. 

Obviously, some of the averages have already been calculated so those wouldn't be necessary.

My hunch is that we will end up calculating any potentially *comparative* data (e.g. # of meetups per year, % of meetups by region) and should prepare for it.
