### ISSUE TITLE
Clone site, update PrimaryStats with Meetups data

### ISSUE THREAD

**Issue by as-dr** [makerdao/commdev-grants-transparency-dashboard#8]
The process for creating the `/meetups` page of the dashboard is to duplicate the existing site (being used to present Grants Program data) and customize it with meetups-specific content.

# To Do
1. - [x] Create a `meetups.jsx` page and populate it with the site `/Layouts` per the existing design.
1. - [x] Once issue #7 is completed, pull in the meetup data into `PrimaryStats`. I believe the best approach here is to rename `PrimaryStats` to `GrantsStats` and create a new `MeetupsStats` with the same code as our "starter", before subsequently updating its design. Can you confirm the best implementation approach @MaximumCrash ?

# Future To-Do's
We need to wait until we know how we are customizing the current "Grantee Projects" section of the site for the `/meetups` page, before creating any to-do's around the customization of that content. 

This will be discussed in issue #5

**Comment by MaximumCrash** [comment]
@as-dr I agree with point 2 of the ToDo. Since PrimaryStats is directly tied to the GrantsPage a few name changes will be needed. Especially if we expect the Grants page and the Meetups page to use different components structurally.

**Comment by as-dr** [comment]
Who wanted to take this one on? 😎

**Comment by MaximumCrash** [comment]
This has been completed as of this PR: https://github.com/makerdao/commdev-grants-transparency-dashboard/pull/16
